// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface SiteChrome {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  brand_name: string;
  nav_home?: string;
  footer_brand_name?: string;
  footer_about?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SitePage {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  hero_kicker?: string;
  hero_title: string;
  hero_body?: string;
  hero_subtext?: string;
  hero_side_note?: string;
  generator_title?: string;
  generator_body?: string;
  nine_centres_eyebrow?: string;
  nine_centres_title?: string;
  concepts_eyebrow?: string;
  concepts_title?: string;
  types_eyebrow?: string;
  types_title?: string;
  types_hint?: string;
  readings_eyebrow?: string;
  readings_title?: string;
  readings_note?: string;
  how_eyebrow?: string;
  how_title?: string;
  letters_eyebrow?: string;
  faq_eyebrow?: string;
  faq_title?: string;
  articles_eyebrow?: string;
  articles_title?: string;
  articles_view_all?: string;
  final_cta_title?: string;
  final_cta_button?: string;
  hero_primary_cta?: string;
  hero_secondary_cta?: string;
  feature_1_title?: string;
  feature_1_body?: string;
  feature_2_title?: string;
  feature_2_body?: string;
  feature_3_title?: string;
  feature_3_body?: string;
  footer_note?: string;
  not_found_title?: string;
  not_found_body?: string;
  not_found_cta?: string;
  seo_title: string;
  seo_description?: string;
  seo_canonical_path?: string;
  seo_robots?: string;
  og_title?: string;
  og_description?: string;
  og_image?: string;
  og_image_alt?: string;
  twitter_card?: string;
  twitter_title?: string;
  twitter_description?: string;
  twitter_image?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    site_chrome: SiteChrome;
    site_pages: SitePage;
  }
}